-- AlterTable
ALTER TABLE "usuario" ADD COLUMN "cep" TEXT NOT NULL DEFAULT '';
ALTER TABLE "usuario" ADD COLUMN "estado" TEXT NOT NULL DEFAULT '';
ALTER TABLE "usuario" ADD COLUMN "cidade" TEXT NOT NULL DEFAULT '';
ALTER TABLE "usuario" ADD COLUMN "rua" TEXT NOT NULL DEFAULT '';
ALTER TABLE "usuario" ADD COLUMN "numero" TEXT NOT NULL DEFAULT '';
ALTER TABLE "usuario" ADD COLUMN "complemento" TEXT;
