services:
  migrate:
      build:
        context: .
        target: builder
      container_name: gestor-academico-migrate
      environment:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/gestor_academico
      command: npx prisma migrate deploy
      depends_on:
        db:
          condition: service_healthy
        
  usuarios-ms:
    build:
      context: .
      target: builder
    container_name: gestor-academico-usuarios-ms
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/gestor_academico
      NODE_ENV: development
      USERS_MS_PORT: 4001
      USERS_MS_BIND: 0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:usuarios-ms:dev
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  turmas-ms:
    build:
      context: .
      target: builder
    container_name: gestor-academico-turmas-ms
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/gestor_academico
      NODE_ENV: development
      TURMAS_MS_PORT: 4002
      TURMAS_MS_BIND: 0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:turmas-ms:dev
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  gateway:
    build:
      context: .
      target: builder
    container_name: gestor-academico-dev
    ports:
      - '3001:3000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/gestor_academico
      NODE_ENV: development
      USERS_MS_HOST: usuarios-ms
      USERS_MS_PORT: 4001
      TURMAS_MS_HOST: turmas-ms
      TURMAS_MS_PORT: 4002
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      usuarios-ms:
        condition: service_started
      turmas-ms:
        condition: service_started

  db:
    image: postgres:16-alpine
    platform: linux/amd64
    container_name: postgres-dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestor_academico
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data_dev:
  pgadmin_data: