-- AlterTable
ALTER TABLE "usuario" ALTER COLUMN "cep" DROP DEFAULT,
ALTER COLUMN "estado" DROP DEFAULT,
ALTER COLUMN "cidade" DROP DEFAULT,
ALTER COLUMN "rua" DROP DEFAULT,
ALTER COLUMN "numero" DROP DEFAULT;
