/** Injection tokens TCP — ficheiro dedicado para evitar import circular com *.gateway.module.ts */
export const USERS_SERVICE_TOKEN = 'USERS_SERVICE';
export const TURMAS_SERVICE_TOKEN = 'TURMAS_SERVICE';
export const CURSOS_SERVICE_TOKEN = 'CURSOS_SERVICE';
export const DISCIPLINAS_SERVICE_TOKEN = 'DISCIPLINAS_SERVICE';
export const MATRICULAS_SERVICE_TOKEN = 'MATRICULAS_SERVICE';
export const AULAS_SERVICE_TOKEN = 'AULAS_SERVICE';
export const ALUNOS_SERVICE_TOKEN = 'ALUNOS_SERVICE';
export const PROFESSORES_SERVICE_TOKEN = 'PROFESSORES_SERVICE';
export const ALUNOS_TURMA_SERVICE_TOKEN = 'ALUNOS_TURMA_SERVICE';
export const INSCRICOES_PROFESSOR_SERVICE_TOKEN =
  'INSCRICOES_PROFESSOR_SERVICE';
